name: Create Or Update Repo

on:
  workflow_dispatch:
    inputs:
      repo_name:
        description: 'Name of the repo to create'
        required: true
        type: string
      is_public_repo:
        description: if unchecked, repo is private.
        required: true
        default: false
        type: boolean
      package_import_name:
        description: Used in imports, e.g. 'from <name> import ...'
        required: true
        type: string

env:
  GH_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}

jobs:
  create-repo-if-not-exists:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Configure git user
        run: |
          git config --global user.email "fares201040@hotmail.com"
          git config --global user.nam "fares201040"
      - run: |
          bash -x run.sh create-repo-if-not-exists
        env:
          REPO_NAME: ${{ github.event.inputs.repo_name }}
          GITHUB_USERNAME: fares201040
          IS_PUBLIC_REPO: ${{ github.event.inputs.is_public_repo }}

  configure-repo:
    needs: [create-repo-if-not-exists]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Configure git user
        run: |
          git config --global user.email "fares201040@hotmail.com"
          git config --global user.nam "fares201040"
      - run: |
          bash -x run.sh configure-repo
        env:
          TEST_PYPI_TOKEN: ${{ secrets.TEST_PYPI_TOKEN }}
          PROD_PYPI_TOKEN: ${{ secrets.PROD_PYPI_TOKEN }}
          REPO_NAME: ${{ github.event.inputs.repo_name }}
          GITHUB_USERNAME: fares201040

  open-pr-with-generated-project:
    needs: [create-repo-if-not-exists]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Configure git user
        run: |
          git config --global user.email "fares201040@hotmail.com"
          git config --global user.nam "fares201040"
      - run: |
          bash -x run.sh open-pr-with-generated-project
        env:
          REPO_NAME: ${{ github.event.inputs.repo_name }}
          GITHUB_USERNAME: fares201040
